services:
  danp:
    image: ghcr.io/macphil/danp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    networks:
      - internal
networks:
  internal:
    driver: bridge
